[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
splendor_arena = { version = "0.1.9", features = ["python_stubs"] }

[lib]
name = "ffi"
crate-type = ["cdylib"]
